spring.application.name=ai-smart-quiz


spring.datasource.url=jdbc:mysql://localhost:3306/ai_smart_quiz
spring.datasource.username=root
spring.datasource.password=kshitiz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

groq.api.key=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

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
jwt.secret=ThisIsMySuperSecretKeyForAiSmartQuizPlatform2026SpringBootJWT
jwt.expiration=86400000